#!/usr/bin/env bash
set -euo pipefail

H="$HOME"
LS="$H/.local/share"
C="$H/.config"
E="/etc"

DOTFILES_DIR="$H/Lit/dotfiles"

SYS_FILES=(
#     "$E/conf.d/wireless-regdom"
#     "$E/firewalld/zones/block.xml"
#     "$E/firewalld/firewalld.conf"
#     "$E/iwd/main.conf"
#     "$E/modprobe.d/wifi.conf"
#     "$E/NetworkManager/conf.d/dns.conf"
#     "$E/resolv.conf"
#     "$E/dnsmasq.conf"
#     "$E/dnsmasq-resolv.conf"
#     "$E/resolvconf.conf"
#     "$E/nsswitch.conf"
#     "$E/chrony.conf"
# #   "$E/polkit-1/rules.d/10-udisks2-mount.rules"
#     "$E/makepkg.conf.d/99-parallel.conf"
#     "$E/mkinitcpio.conf"
#     "$E/mkinitcpio.d/linux.preset"
#     "$E/ly/config.ini"
#     "$E/ly/save.ini"
#     "$E/conf.d/pacman-contrib"
#     "$E/pacman.conf"
#     "$E/paru.conf"
#     "/boot/loader/loader.conf"
    "$C/nvim/lua/keymaps.lua"
    "$H/.zshrc"
    "$H/.zsh_history"
    "$H/.gitconfig"
    "$LS/org.kde.syntax-highlighting"
    "$LS/recently-used.xbel"
    "$LS/user-places.xbel"
    "$C/arkrc"
    "$C/auroraerc"
    "$C/baloofilerc"
    "$C/dolphinrc"
    "$C/kalarmrc"
    "$C/kate-externaltoolspluginrc"
    "$C/katerc"
    "$C/katevirc"
    "$C/kcminputrc"
    "$C/kconf_updaterc"
    "$C/kdeglobals"
    "$C/kglobalshortcutsrc"
    "$C/kiorc"
    "$C/klipperrc"
    "$C/kmenueditrc"
    "$C/knightsrc"
    "$C/kscreenlockerrc"
    "$C/ksmserverrc"
    "$C/ksplashrc"
    "$C/kwinrc"
    "$C/kwinoutputconfig.json"
    "$C/mimeapps.list"
    "$C/okularpartrc"
    "$C/plasmarc"
    "$C/plasmashellrc"
    "$C/powerdevilrc"
    "$C/qBittorrent/qBittorrent.conf"
)

for file in "${SYS_FILES[@]}"; do
    src="$file"
    dest="$DOTFILES_DIR$file"   # preserve full path under dotfiles

    mkdir -p "$(dirname "$dest")"

    cp -a "$src" "$dest"
    echo "Copied $src → $dest"
done
